### ISSUE TITLE
You must link with -lpthread on linux.

### ISSUE THREAD

**Issue by AWoloszyn** [google/marl#60] opened 2019-11-18 21:50 UTC
I noticed that when marl, embedded in another library is loaded, it will crash without `-lpthread` on linux.

Not sure what the right solution is, maybe trying to dynamically load pthreads when run?

**Comment by ben-clayton** [comment] 2019-11-19 15:38
#61 builds and runs the tests and examples without directly linking `pthread` (it should already be linked due to the dependency on the `marl` target`).
I have to say, I'm a little perplexed by this one.

**Comment by ben-clayton** [comment] 2019-11-30 12:15
@AWoloszyn what do you want to do with this bug?

**Comment by myd7349** [comment] 2020-02-13 04:36
Hi! @AWoloszyn Did you use CMake as the build tool? If so, could give this patch a try? https://github.com/myd7349/marl/commit/5d0691565ecd75402ab1b7c08864d39230bd2886
Thanks!

**Comment by ben-clayton** [comment] 2020-03-06 10:41
@myd7349 - @AWoloszyn seems rather busy.
If it's okay with you, shall we merge your change?

It looks like a more idiomatic way of using CMake, and could fix this issue that I've been unable to reproduce.

**Comment by ben-clayton** [comment] 2020-03-23 14:20
Fixed by https://github.com/google/marl/pull/108.

**Closed by ben-clayton** 2020-03-23 14:20 UTC
