### ISSUE TITLE
[question] enabling support for new architecture -- riscv64

### ISSUE THREAD

**Issue by rebeccasf** [google/marl#207] opened 2021-12-06 08:07 UTC
Hi, I am working on porting software stacks onto RISC-V architecture.
I came across this as one of the dependency and I would like to know more about the code in order for me to enable RISC-V.
Is there any porting guide for this?
I noticed that we need to provide the hardware register mapping and some assembly language file within the src directory.
I would like to know some good starting point

**Comment by rebeccasf** [comment] 2021-12-07 01:07
Thank you Ben. I will try to code it out and submit for review when it is ready.

**Comment by developandplay** [comment] 2021-12-20 14:51
@ben-clayton Thank you for providing this guide. As you said it was pretty straight forward.

I did manage to follow through with it and all tests now pass for riscv64.
However I'm currently running into an unhandled signal issue with the `AllocatorTest.Guards`.
The test case still passes but since I couldn't reproduce the unhandled signal on x86 there is probably something wrong with it.
Could you provide a bit more insight into the `AllocatorTest.Guards` test case?
Maybe we can then figure out the cause and fix it.

For context: I'm planning to port Swiftshader to RISC-V so I need to port marl first.

**Comment by developandplay** [comment] 2021-12-20 16:57
Now that I had another look at it:
https://github.com/google/marl/blob/e82d1a7b8bca94cca68e0000e866289e2cf29ccc/src/memory_test.cpp#L78-L89
It seems like the test case on purpose tries to provoke an issue so the behavior (+passing the test case) probably is correct.
That being said googletest probably shouldn't pass the exception output to the user if these exceptions are expected behavior.
I'm not sure why passing the exception output to the user happens on risc-v but not on x86.

**Comment by ben-clayton** [comment] 2021-12-24 01:22
https://github.com/google/marl/pull/208 has landed. I believe this addresses this issue. Closing.

**Closed by ben-clayton** 2021-12-24 01:22 UTC
